countries = [ { name: "Afghanistan", phone_code: "93" }, 
{ name: "Albania", phone_code: "355" }, 
{ name: "Algeria", phone_code: "213" }, 
{ name: "American Samoa", phone_code: "1-684" }, 
{ name: "Andorra", phone_code: "376" }, 
{ name: "Angola", phone_code: "244" }, 
{ name: "Anguilla", phone_code: "1-264" }, 
{ name: "Antarctica", phone_code: "672" }, 
{ name: "Antigua and Barbuda", phone_code: "1-268" }, 
{ name: "Argentina", phone_code: "54" }, 
{ name: "Armenia", phone_code: "374" }, 
{ name: "Aruba", phone_code: "297" }, 
{ name: "Australia", phone_code: "61" }, 
{ name: "Austria", phone_code: "43" }, 
{ name: "Azerbaijan", phone_code: "994" }, 
{ name: "Bahamas", phone_code: "1-242" }, 
{ name: "Bahrain", phone_code: "973" }, 
{ name: "Bangladesh", phone_code: "880" }, 
{ name: "Barbados", phone_code: "1-246" }, 
{ name: "Belarus", phone_code: "375" }, 
{ name: "Belgium", phone_code: "32" }, 
{ name: "Belize", phone_code: "501" }, 
{ name: "Benin", phone_code: "229" }, 
{ name: "Bermuda", phone_code: "1-441" }, 
{ name: "Bhutan", phone_code: "975" }, 
{ name: "Bolivia", phone_code: "591" }, 
{ name: "Bosnia and Herzegovina", phone_code: "387" }, 
{ name: "Botswana", phone_code: "267" }, 
{ name: "Brazil", phone_code: "55" }, 
{ name: "British Indian Ocean Territory", phone_code: "246" }, 
{ name: "British Virgin Islands", phone_code: "1-284" }, 
{ name: "Brunei", phone_code: "673" }, 
{ name: "Bulgaria", phone_code: "359" }, 
{ name: "Burkina Faso", phone_code: "226" }, 
{ name: "Burundi", phone_code: "257" }, 
{ name: "Cambodia", phone_code: "855" }, 
{ name: "Cameroon", phone_code: "237" }, 
{ name: "Canada", phone_code: "1" }, 
{ name: "Cape Verde", phone_code: "238" }, 
{ name: "Cayman Islands", phone_code: "1-345" }, 
{ name: "Central African Republic", phone_code: "236" }, 
{ name: "Chad", phone_code: "235" }, 
{ name: "Chile", phone_code: "56" }, 
{ name: "China", phone_code: "86" }, 
{ name: "Christmas Island", phone_code: "61" }, 
{ name: "Cocos Islands", phone_code: "61" }, 
{ name: "Colombia", phone_code: "57" }, 
{ name: "Comoros", phone_code: "269" }, 
{ name: "Cook Islands", phone_code: "682" }, 
{ name: "Costa Rica", phone_code: "506" }, 
{ name: "Croatia", phone_code: "385" }, 
{ name: "Cuba", phone_code: "53" }, 
{ name: "Curacao", phone_code: "599" }, 
{ name: "Cyprus", phone_code: "357" }, 
{ name: "Czech Republic", phone_code: "420" }, 
{ name: "Democratic Republic of the Congo", phone_code: "243" }, 
{ name: "Denmark", phone_code: "45" }, 
{ name: "Djibouti", phone_code: "253" }, 
{ name: "Dominica", phone_code: "1-767" }, 
{ name: "Dominican Republic", phone_code: "1-809" }, 
{ name: "East Timor", phone_code: "670" }, 
{ name: "Ecuador", phone_code: "593" }, 
{ name: "Egypt", phone_code: "20" }, 
{ name: "El Salvador", phone_code: "503" }, 
{ name: "Equatorial Guinea", phone_code: "240" }, 
{ name: "Eritrea", phone_code: "291" }, 
{ name: "Estonia", phone_code: "372" }, 
{ name: "Ethiopia", phone_code: "251" }, 
{ name: "Falkland Islands", phone_code: "500" }, 
{ name: "Faroe Islands", phone_code: "298" }, 
{ name: "Fiji", phone_code: "679" }, 
{ name: "Finland", phone_code: "358" }, 
{ name: "France", phone_code: "33" }, 
{ name: "French Polynesia", phone_code: "689" }, 
{ name: "Gabon", phone_code: "241" }, 
{ name: "Gambia", phone_code: "220" }, 
{ name: "Georgia", phone_code: "995" }, 
{ name: "Germany", phone_code: "49" }, 
{ name: "Ghana", phone_code: "233" }, 
{ name: "Gibraltar", phone_code: "350" }, 
{ name: "Greece", phone_code: "30" }, 
{ name: "Greenland", phone_code: "299" }, 
{ name: "Grenada", phone_code: "1-473" }, 
{ name: "Guam", phone_code: "1-671" }, 
{ name: "Guatemala", phone_code: "502" }, 
{ name: "Guernsey", phone_code: "44-1481" }, 
{ name: "Guinea", phone_code: "224" }, 
{ name: "Guinea-Bissau", phone_code: "245" }, 
{ name: "Guyana", phone_code: "592" }, 
{ name: "Haiti", phone_code: "509" }, 
{ name: "Honduras", phone_code: "504" }, 
{ name: "Hong Kong", phone_code: "852" }, 
{ name: "Hungary", phone_code: "36" }, 
{ name: "Iceland", phone_code: "354" }, 
{ name: "India", phone_code: "91" }, 
{ name: "Indonesia", phone_code: "62" }, 
{ name: "Iran", phone_code: "98" }, 
{ name: "Iraq", phone_code: "964" }, 
{ name: "Ireland", phone_code: "353" }, 
{ name: "Isle of Man", phone_code: "44-1624" }, 
{ name: "Israel", phone_code: "972" }, 
{ name: "Italy", phone_code: "39" }, 
{ name: "Ivory Coast", phone_code: "225" }, 
{ name: "Jamaica", phone_code: "1-876" }, 
{ name: "Japan", phone_code: "81" }, 
{ name: "Jersey", phone_code: "44-1534" }, 
{ name: "Jordan", phone_code: "962" }, 
{ name: "Kazakhstan", phone_code: "7" }, 
{ name: "Kenya", phone_code: "254" }, 
{ name: "Kiribati", phone_code: "686" }, 
{ name: "Kosovo", phone_code: "383" }, 
{ name: "Kuwait", phone_code: "965" }, 
{ name: "Kyrgyzstan", phone_code: "996" }, 
{ name: "Laos", phone_code: "856" }, 
{ name: "Latvia", phone_code: "371" }, 
{ name: "Lebanon", phone_code: "961" }, 
{ name: "Lesotho", phone_code: "266" }, 
{ name: "Liberia", phone_code: "231" }, 
{ name: "Libya", phone_code: "218" }, 
{ name: "Liechtenstein", phone_code: "423" }, 
{ name: "Lithuania", phone_code: "370" }, 
{ name: "Luxembourg", phone_code: "352" }, 
{ name: "Macao", phone_code: "853" }, 
{ name: "Macedonia", phone_code: "389" }, 
{ name: "Madagascar", phone_code: "261" }, 
{ name: "Malawi", phone_code: "265" }, 
{ name: "Malaysia", phone_code: "60" }, 
{ name: "Maldives", phone_code: "960" }, 
{ name: "Mali", phone_code: "223" }, 
{ name: "Malta", phone_code: "356" }, 
{ name: "Marshall Islands", phone_code: "692" }, 
{ name: "Mauritania", phone_code: "222" }, 
{ name: "Mauritius", phone_code: "230" }, 
{ name: "Mayotte", phone_code: "262" }, 
{ name: "Mexico", phone_code: "52" }, 
{ name: "Micronesia", phone_code: "691" }, 
{ name: "Moldova", phone_code: "373" }, 
{ name: "Monaco", phone_code: "377" }, 
{ name: "Mongolia", phone_code: "976" }, 
{ name: "Montenegro", phone_code: "382" }, 
{ name: "Montserrat", phone_code: "1-664" }, 
{ name: "Morocco", phone_code: "212" }, 
{ name: "Mozambique", phone_code: "258" }, 
{ name: "Myanmar", phone_code: "95" }, 
{ name: "Namibia", phone_code: "264" }, 
{ name: "Nauru", phone_code: "674" }, 
{ name: "Nepal", phone_code: "977" }, 
{ name: "Netherlands", phone_code: "31" }, 
{ name: "Netherlands Antilles", phone_code: "599" }, 
{ name: "New Caledonia", phone_code: "687" }, 
{ name: "New Zealand", phone_code: "64" }, 
{ name: "Nicaragua", phone_code: "505" }, 
{ name: "Niger", phone_code: "227" }, 
{ name: "Nigeria", phone_code: "234" }, 
{ name: "Niue", phone_code: "683" }, 
{ name: "North Korea", phone_code: "850" }, 
{ name: "Northern Mariana Islands", phone_code: "1-670" }, 
{ name: "Norway", phone_code: "47" }, 
{ name: "Oman", phone_code: "968" }, 
{ name: "Pakistan", phone_code: "92" }, 
{ name: "Palau", phone_code: "680" }, 
{ name: "Palestine", phone_code: "970" }, 
{ name: "Panama", phone_code: "507" }, 
{ name: "Papua New Guinea", phone_code: "675" }, 
{ name: "Paraguay", phone_code: "595" }, 
{ name: "Peru", phone_code: "51" }, 
{ name: "Philippines", phone_code: "63" }, 
{ name: "Pitcairn", phone_code: "64" }, 
{ name: "Poland", phone_code: "48" }, 
{ name: "Portugal", phone_code: "351" }, 
{ name: "Puerto Rico", phone_code: "1-787" }, 
{ name: "Qatar", phone_code: "974" }, 
{ name: "Republic of the Congo", phone_code: "242" }, 
{ name: "Reunion", phone_code: "262" }, 
{ name: "Romania", phone_code: "40" }, 
{ name: "Russia", phone_code: "7" }, 
{ name: "Rwanda", phone_code: "250" }, 
{ name: "Saint Barthelemy", phone_code: "590" }, 
{ name: "Saint Helena", phone_code: "290" }, 
{ name: "Saint Kitts and Nevis", phone_code: "1-869" }, 
{ name: "Saint Lucia", phone_code: "1-758" }, 
{ name: "Saint Martin", phone_code: "590" }, 
{ name: "Saint Pierre and Miquelon", phone_code: "508" }, 
{ name: "Saint Vincent and the Grenadines", phone_code: "1-784" }, 
{ name: "Samoa", phone_code: "685" }, 
{ name: "San Marino", phone_code: "378" }, 
{ name: "Sao Tome and Principe", phone_code: "239" }, 
{ name: "Saudi Arabia", phone_code: "966" }, 
{ name: "Senegal", phone_code: "221" }, 
{ name: "Serbia", phone_code: "381" }, 
{ name: "Seychelles", phone_code: "248" }, 
{ name: "Sierra Leone", phone_code: "232" }, 
{ name: "Singapore", phone_code: "65" }, 
{ name: "Sint Maarten", phone_code: "1-721" }, 
{ name: "Slovakia", phone_code: "421" }, 
{ name: "Slovenia", phone_code: "386" }, 
{ name: "Solomon Islands", phone_code: "677" }, 
{ name: "Somalia", phone_code: "252" }, 
{ name: "South Africa", phone_code: "27" }, 
{ name: "South Korea", phone_code: "82" }, 
{ name: "South Sudan", phone_code: "211" }, 
{ name: "Spain", phone_code: "34" }, 
{ name: "Sri Lanka", phone_code: "94" }, 
{ name: "Sudan", phone_code: "249" }, 
{ name: "Suriname", phone_code: "597" }, 
{ name: "Svalbard and Jan Mayen", phone_code: "47" }, 
{ name: "Swaziland", phone_code: "268" }, 
{ name: "Sweden", phone_code: "46" }, 
{ name: "Switzerland", phone_code: "41" }, 
{ name: "Syria", phone_code: "963" }, 
{ name: "Taiwan", phone_code: "886" }, 
{ name: "Tajikistan", phone_code: "992" }, 
{ name: "Tanzania", phone_code: "255" }, 
{ name: "Thailand", phone_code: "66" }, 
{ name: "Togo", phone_code: "228" }, 
{ name: "Tokelau", phone_code: "690" }, 
{ name: "Tonga", phone_code: "676" }, 
{ name: "Trinidad and Tobago", phone_code: "1-868" }, 
{ name: "Tunisia", phone_code: "216" }, 
{ name: "Turkey", phone_code: "90" }, 
{ name: "Turkmenistan", phone_code: "993" }, 
{ name: "Turks and Caicos Islands", phone_code: "1-649" }, 
{ name: "Tuvalu", phone_code: "688" }, 
{ name: "U.S. Virgin Islands", phone_code: "1-340" }, 
{ name: "Uganda", phone_code: "256" }, 
{ name: "Ukraine", phone_code: "380" }, 
{ name: "United Arab Emirates", phone_code: "971" }, 
{ name: "United Kingdom", phone_code: "44" }, 
{ name: "United States", phone_code: "1" }, 
{ name: "Uruguay", phone_code: "598" }, 
{ name: "Uzbekistan", phone_code: "998" }, 
{ name: "Vanuatu", phone_code: "678" }, 
{ name: "Vatican", phone_code: "379" }, 
{ name: "Venezuela", phone_code: "58" }, 
{ name: "Vietnam", phone_code: "84" }, 
{ name: "Wallis and Futuna", phone_code: "681" }, 
{ name: "Western Sahara", phone_code: "212" }, 
{ name: "Yemen", phone_code: "967" }, 
{ name: "Zambia", phone_code: "260" }, 
{ name: "Zimbabwe", phone_code: "263" }]

Country.delete_all
Country.create(countries)

currencies = [ { code: "USD", name:"US Dollar", rate: 1.0000 },
{ code: "EUR", name:"Euro", rate: 0.8772 },
{ code: "GBP", name:"British Pound", rate: 0.7031 },
{ code: "INR", name:"Indian Rupee", rate: 66.2299 },
{ code: "AUD", name:"Australian Dollar", rate: 1.3036 },
{ code: "CAD", name:"Canadian Dollar", rate: 1.3029 },
{ code: "SGD", name:"Singapore Dollar", rate: 1.3502 },
{ code: "CHF", name:"Swiss Franc", rate: 0.9582 },
{ code: "MYR", name:"Malaysian Ringgit", rate: 3.8805 },
{ code: "JPY", name:"Japanese Yen", rate: 111.6130 },
{ code: "CNY", name:"Chinese Yuan Renminbi", rate: 6.4776 },
{ code: "NZD", name:"New Zealand Dollar", rate: 1.4516 },
{ code: "THB", name:"Thai Baht", rate: 35.1308 },
{ code: "HUF", name:"Hungarian Forint", rate: 274.9534 },
{ code: "AED", name:"Emirati Dirham", rate: 3.6724 },
{ code: "HKD", name:"Hong Kong Dollar", rate: 7.7547 },
{ code: "MXN", name:"Mexican Peso", rate: 17.3317 },
{ code: "ZAR", name:"South African Rand", rate: 14.7303 },
{ code: "PHP", name:"Philippine Peso", rate: 46.0850 },
{ code: "SEK", name:"Swedish Krona", rate: 8.1130 },
{ code: "IDR", name:"Indonesian Rupiah", rate: 13155.9999 },
{ code: "SAR", name:"Saudi Arabian Riyal", rate: 3.7502 },
{ code: "BRL", name:"Brazilian Real", rate: 3.5534 },
{ code: "TRY", name:"Turkish Lira", rate: 2.8225 },
{ code: "KES", name:"Kenyan Shilling", rate: 101.3699 },
{ code: "KRW", name:"South Korean Won", rate: 1147.9499 },
{ code: "EGP", name:"Egyptian Pound", rate: 8.8802 },
{ code: "IQD", name:"Iraqi Dinar", rate: 1106.3660 },
{ code: "NOK", name:"Norwegian Krone", rate: 8.3092 },
{ code: "KWD", name:"Kuwaiti Dinar", rate: 0.3018 },
{ code: "RUB", name:"Russian Ruble", rate: 67.3650 },
{ code: "DKK", name:"Danish Krone", rate: 6.5341 },
{ code: "PKR", name:"Pakistani Rupee", rate: 104.7199 },
{ code: "ILS", name:"Israeli Shekel", rate: 3.7706 },
{ code: "PLN", name:"Polish Zloty", rate: 3.7269 },
{ code: "QAR", name:"Qatari Riyal", rate: 3.6413 },
{ code: "XAU", name:"Gold Ounce", rate: 0.0008 },
{ code: "OMR", name:"Omani Rial", rate: 0.3850 },
{ code: "COP", name:"Colombian Peso", rate: 3034.2000 },
{ code: "CLP", name:"Chilean Peso", rate: 669.0037 },
{ code: "TWD", name:"Taiwan New Dollar", rate: 32.2399 },
{ code: "ARS", name:"Argentine Peso", rate: 14.6895 },
{ code: "CZK", name:"Czech Koruna", rate: 23.7094 },
{ code: "VND", name:"Vietnamese Dong", rate: 22294.9999 },
{ code: "MAD", name:"Moroccan Dirham", rate: 9.6054 },
{ code: "JOD", name:"Jordanian Dinar", rate: 0.7085 },
{ code: "BHD", name:"Bahraini Dinar", rate: 0.3769 },
{ code: "XOF", name:"CFA Franc", rate: 575.4399 },
{ code: "LKR", name:"Sri Lankan Rupee", rate: 146.2204 },
{ code: "UAH", name:"Ukrainian Hryvnia", rate: 26.0249 },
{ code: "NGN", name:"Nigerian Naira", rate: 198.8500 },
{ code: "TND", name:"Tunisian Dinar", rate: 1.9982 },
{ code: "UGX", name:"Ugandan Shilling", rate: 3365.9999 },
{ code: "RON", name:"Romanian New Leu", rate: 3.9184 },
{ code: "BDT", name:"Bangladeshi Taka", rate: 78.2249 },
{ code: "PEN", name:"Peruvian Sol", rate: 3.3165 },
{ code: "GEL", name:"Georgian Lari", rate: 2.2948 },
{ code: "XAF", name:"Central African CFA Franc BEAC", rate: 575.4399 },
{ code: "FJD", name:"Fijian Dollar", rate: 2.0768 },
{ code: "VEF", name:"Venezuelan Bolivar", rate: 6.3496 },
{ code: "BYR", name:"Belarusian Ruble", rate: 19988.5000 },
{ code: "HRK", name:"Croatian Kuna", rate: 6.5846 },
{ code: "UZS", name:"Uzbekistani Som", rate: 2871.7477 },
{ code: "BGN", name:"Bulgarian Lev", rate: 1.7164 },
{ code: "DZD", name:"Algerian Dinar", rate: 108.1700 },
{ code: "IRR", name:"Iranian Rial", rate: 30165.0000 },
{ code: "DOP", name:"Dominican Peso", rate: 45.7800 },
{ code: "ISK", name:"Icelandic Krona", rate: 123.1548 },
{ code: "XAG", name:"Silver Ounce", rate: 0.0664 },
{ code: "CRC", name:"Costa Rican Colon", rate: 531.0999 },
{ code: "SYP", name:"Syrian Pound", rate: 188.8160 },
{ code: "LYD", name:"Libyan Dinar", rate: 1.3400 },
{ code: "JMD", name:"Jamaican Dollar", rate: 121.3999 },
{ code: "MUR", name:"Mauritian Rupee", rate: 35.1800 },
{ code: "GHS", name:"Ghanaian Cedi", rate: 3.8399 },
{ code: "AOA", name:"Angolan Kwanza", rate: 160.5370 },
{ code: "UYU", name:"Uruguayan Peso", rate: 31.7299 },
{ code: "AFN", name:"Afghan Afghani", rate: 68.5199 },
{ code: "LBP", name:"Lebanese Pound", rate: 1506.1000 },
{ code: "XPF", name:"CFP Franc", rate: 104.6840 },
{ code: "TTD", name:"Trinidadian Dollar", rate: 6.5585 },
{ code: "TZS", name:"Tanzanian Shilling", rate: 2182.7000 },
{ code: "ALL", name:"Albanian Lek", rate: 121.8243 },
{ code: "XCD", name:"East Caribbean Dollar", rate: 2.7000 },
{ code: "GTQ", name:"Guatemalan Quetzal", rate: 7.7107 },
{ code: "NPR", name:"Nepalese Rupee", rate: 105.9559 },
{ code: "BOB", name:"Bolivian Bol", rate: 6.7799 },
{ code: "ZWD", name:"Zimbabwean Dollar", rate: 361.9000 },
{ code: "BBD", name:"Barbadian or Bajan Dollar", rate: 2.0000 },
{ code: "CUC", name:"Cuban Convertible Peso", rate: 1.0000 },
{ code: "LAK", name:"Lao or Laotian Kip", rate: 8101.5000 },
{ code: "BND", name:"Bruneian Dollar", rate: 1.3502 },
{ code: "BWP", name:"Botswana Pula", rate: 10.8341 },
{ code: "HNL", name:"Honduran Lempira", rate: 22.5599 },
{ code: "PYG", name:"Paraguayan Guarani", rate: 5618.0000 },
{ code: "ETB", name:"Ethiopian Birr", rate: 21.4644 },
{ code: "NAD", name:"Namibian Dollar", rate: 14.7303 },
{ code: "PGK", name:"Papua New Guinean Kina", rate: 3.0769 },
{ code: "SDG", name:"Sudanese Pound", rate: 6.0725 },
{ code: "MOP", name:"Macau Pataca", rate: 7.9873 },
{ code: "NIO", name:"Nicaraguan Cordoba", rate: 28.2728 },
{ code: "BMD", name:"Bermudian Dollar", rate: 1.0000 },
{ code: "KZT", name:"Kazakhstani Tenge", rate: 342.3550 },
{ code: "PAB", name:"Panamanian Balboa", rate: 1.0000 },
{ code: "BAM", name:"Bosnian Convertible Marka", rate: 1.7157 },
{ code: "GYD", name:"Guyanese Dollar", rate: 204.6000 },
{ code: "YER", name:"Yemeni Rial", rate: 214.8600 },
{ code: "MGA", name:"Malagasy Ariary", rate: 3180.9999 },
{ code: "KYD", name:"Caymanian Dollar", rate: 0.8199 },
{ code: "MZN", name:"Mozambican Metical", rate: 50.4700 },
{ code: "RSD", name:"Serbian Dinar", rate: 107.7947 },
{ code: "SCR", name:"Seychellois Rupee", rate: 13.2500 },
{ code: "AMD", name:"Armenian Dram", rate: 481.2597 },
{ code: "SBD", name:"Solomon Islander Dollar", rate: 7.9365 },
{ code: "AZN", name:"Azerbaijani New Manat", rate: 1.5183 },
{ code: "SLL", name:"Sierra Leonean Leone", rate: 3954.0000 },
{ code: "TOP", name:"Tongan Paanga", rate: 2.2670 },
{ code: "BZD", name:"Belizean Dollar", rate: 1.9835 },
{ code: "MWK", name:"Malawian Kwacha", rate: 677.3499 },
{ code: "GMD", name:"Gambian Dalasi", rate: 42.5199 },
{ code: "BIF", name:"Burundian Franc", rate: 1532.1999 },
{ code: "SOS", name:"Somali Shilling", rate: 609.1024 },
{ code: "HTG", name:"Haitian Gourde", rate: 61.7199 },
{ code: "GNF", name:"Guinean Franc", rate: 7495.0000 },
{ code: "MVR", name:"Maldivian Rufiyaa", rate: 15.3499 },
{ code: "MNT", name:"Mongolian Tughrik", rate: 2045.4999 },
{ code: "CDF", name:"Congolese Franc", rate: 914.0000 },
{ code: "STD", name:"Sao Tomean Dobra", rate: 21429.9999 },
{ code: "TJS", name:"Tajikistani Somoni", rate: 7.8695 },
{ code: "KPW", name:"North Korean Won", rate: 129.4699 },
{ code: "MMK", name:"Burmese Kyat", rate: 1206.5000 },
{ code: "LSL", name:"Basotho Loti", rate: 14.7303 },
{ code: "LRD", name:"Liberian Dollar", rate: 90.0999 },
{ code: "KGS", name:"Kyrgyzstani Som", rate: 69.9991 },
{ code: "GIP", name:"Gibraltar Pound", rate: 0.7031 },
{ code: "XPT", name:"Platinum Ounce", rate: 0.0010 },
{ code: "MDL", name:"Moldovan Leu", rate: 19.4600 },
{ code: "CUP", name:"Cuban Peso", rate: 26.5000 },
{ code: "KHR", name:"Cambodian Riel", rate: 4006.9999 },
{ code: "MKD", name:"Macedonian Denar", rate: 53.9799 },
{ code: "VUV", name:"Ni-Vanuatu Vatu", rate: 104.6199 },
{ code: "MRO", name:"Mauritanian Ouguiya", rate: 312.5000 },
{ code: "ANG", name:"Dutch Guilder", rate: 1.7705 },
{ code: "SZL", name:"Swazi Lilangeni", rate: 14.7303 },
{ code: "CVE", name:"Cape Verdean Escudo", rate: 96.5900 },
{ code: "SRD", name:"Surinamese Dollar", rate: 5.0649 },
{ code: "XPD", name:"Palladium Ounce", rate: 0.0017 },
{ code: "SVC", name:"Salvadoran Colon", rate: 8.7500 },
{ code: "BSD", name:"Bahamian Dollar", rate: 1.0000 },
{ code: "XDR", name:"IMF Special Drawing Rights", rate: 0.7100 },
{ code: "RWF", name:"Rwandan Franc", rate: 772.0517 },
{ code: "AWG", name:"Aruban or Dutch Guilder", rate: 1.7900 },
{ code: "DJF", name:"Djiboutian Franc", rate: 176.7000 },
{ code: "BTN", name:"Bhutanese Ngultrum", rate: 66.2299 },
{ code: "KMF", name:"Comoran Franc", rate: 431.5799 },
{ code: "WST", name:"Samoan Tala", rate: 2.6076 },
{ code: "SPL", name:"Seborgan Luigino", rate: 0.1666 },
{ code: "ERN", name:"Eritrean Nakfa", rate: 10.4699 },
{ code: "FKP", name:"Falkland Island Pound", rate: 0.7031 },
{ code: "SHP", name:"Saint Helenian Pound", rate: 0.7031 },
{ code: "JEP", name:"Jersey Pound", rate: 0.7031 },
{ code: "TMT", name:"Turkmenistani Manat", rate: 3.5000 },
{ code: "TVD", name:"Tuvaluan Dollar", rate: 1.3036 },
{ code: "IMP", name:"Isle of Man Pound", rate: 0.7031 },
{ code: "GGP", name:"Guernsey Pound", rate: 0.7031 },
{ code: "ZMW", name:"Zambian Kwacha", rate: 10.9500 }]

Currency.delete_all
Currency.create(currencies)

roles = [
  { name: "User", 
    can_see_products: true, 
    can_create_products: true, 
    can_buy_products: true, 
    can_comment: true,
    can_chat: true },
  { name: "Privileged", 
    can_see_products: true, 
    can_create_products: true, 
    can_create_categories: true, 
    can_buy_products: true, 
    can_comment: true,
    can_chat: true },
  { name: "Moderator", 
    can_see_products: true, 
    can_create_products: true, 
    can_create_categories: true, 
    can_buy_products: true, 
    can_comment: true,
    can_moderate: true,
    can_chat: true,
    can_create_priveleged_users: true },
  { name: "Admin", 
    can_see_products: true, 
    can_create_products: true, 
    can_create_categories: true, 
    can_buy_products: true, 
    can_comment: true,
    can_moderate: true,
    can_chat: true,
    can_see_statistics: true,
    can_create_moderators: true,
    can_create_priveleged_users: true }
]

Role.delete_all
Role.create(roles)

property_types = [
  { name: "String", display_name: "Строка", description: "Текстовое поле высотой в одну строку. Максимальная длина: 50 символов." },
  { name: "Text", display_name: "Текст", description: "Поле для текста. Максимальный объем: 500 символов." },
  { name: "Number", display_name: "Число", description: "Целое или дробное число." },
  { name: "NumberInRange", display_name: "Число в диапазоне", description: "Целое или дробное число с заданным максимумом и минимумом." },
  { name: "Range", display_name: "Диапазон", description: "Диапазон, заданые минимумом и максимумом." },
  { name: "Select", display_name: "Выбор опции", description: "Выбор из заданного набора опций." },
  { name: "Image", display_name: "Изображение", description: "Изображение товара." }
]

PropertyType.delete_all
PropertyType.create(property_types)

categories = [
  { name: "Мопед", description: "Двух- или трёхколёсное транспортное средство с двигателем внутреннего сгорания рабочим объёмом не более 50 кубических сантиметров и максимальной конструктивной скоростью не более 50 км/ч ", avatar_link: "http://minsk-scooter.by/wp-content/uploads/2012/04/moped_viper_delta.jpg", is_archived: false },
  { name: "Супербайк", description: "Неофициальное название дорожных мотоциклов спортивного типа (также Спортбайк), конструкция которых имеет черты, свойственные гоночным мотоциклам", avatar_link: "http://www.goldengod.ru/wp-content/uploads/2009/11/ducati-1198s.jpg", is_archived: false },
  { name: "Чоппер", description: "В отличие от бобберов, у будущего чоппера убирается не только все лишнее — переднее крыло, иногда передний тормоз, глубокое заднее крыло, но также подвергается серьёзной переделке и сама рама.", avatar_link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/ZweiRadMuseumNSU_EasyRider.JPG/250px-ZweiRadMuseumNSU_EasyRider.JPG", is_archived: false },
  { name: "Мотовездеход", description: "Небольшое транспортное средство, похожее на мотоцикл, но имеющее более двух колёс", avatar_link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Aeon_Cobra_220_ATV_Quad_bike.JPG/220px-Aeon_Cobra_220_ATV_Quad_bike.JPG", is_archived: false },
  { name: "Питбайк", description: "Это разновидность мотоцикла, пригодного для мотокросса или супермото.", avatar_link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/PitBike.jpg/200px-PitBike.jpg", is_archived: false }
]

Category.delete_all
Category.create(categories)

#Test data
users_params = [
  { email: "admin@admin.com",
    login: "admin",
    encrypted_password: Digest::SHA2.hexdigest("enigma"),
    first_name: "Admin",
    last_name: "Last name",
    passport_id: "123123123123",
    avatar_url: "123123123",
    address_line_1: "asdasdasd",
    address_line_2: "asdasdasd",
    post_index: "asd123",
    phone_number: "12312312323",
    birth_date: Time.now,
    role_id: Role.where(name: "Admin").first.id,
    country_id: Country.first,
    token: "stub",
    token_expires_at: Time.now + 1.day },

  { email: "moderator@admin.com",
    login: "moderator",
    encrypted_password: Digest::SHA2.hexdigest("enigma"),
    first_name: "Moderator",
    last_name: "Last name",
    passport_id: "123123123123",
    avatar_url: "123123123",
    address_line_1: "asdasdasd",
    address_line_2: "asdasdasd",
    post_index: "asd123",
    phone_number: "12312312323",
    birth_date: Time.now,
    role_id: Role.where(name: "Moderator").first.id,
    country_id: Country.first,
    token: "stub",
    token_expires_at: Time.now + 1.day },

  { email: "priveleged@admin.com",
    login: "Privileged",
    encrypted_password: Digest::SHA2.hexdigest("enigma"),
    first_name: "Privileged",
    last_name: "Last name",
    passport_id: "123123123123",
    avatar_url: "123123123",
    address_line_1: "asdasdasd",
    address_line_2: "asdasdasd",
    post_index: "asd123",
    phone_number: "12312312323",
    birth_date: Time.now,
    role_id: Role.where(name: "Privileged").first.id,
    country_id: Country.first,
    token: "stub",
    token_expires_at: Time.now + 1.day },

  { email: "user1@admin.com",
    login: "User1",
    encrypted_password: Digest::SHA2.hexdigest("enigma"),
    first_name: "User",
    last_name: "Last name",
    passport_id: "123123123123",
    avatar_url: "123123123",
    address_line_1: "asdasdasd",
    address_line_2: "asdasdasd",
    post_index: "asd123",
    phone_number: "12312312323",
    birth_date: Time.now,
    role_id: Role.where(name: "User").first.id,
    country_id: Country.first,
    token: "stub",
    token_expires_at: Time.now + 1.day },

  { email: "User2@admin.com",
    login: "User2",
    encrypted_password: Digest::SHA2.hexdigest("enigma"),
    first_name: "User",
    last_name: "Last name",
    passport_id: "123123123123",
    avatar_url: "123123123",
    address_line_1: "asdasdasd",
    address_line_2: "asdasdasd",
    post_index: "asd123",
    phone_number: "12312312323",
    birth_date: Time.now,
    role_id: Role.where(name: "User").first.id,
    country_id: Country.first,
    token: "stub",
    token_expires_at: Time.now + 1.day }]

  User.delete_all
  users = User.create(users_params);
  users.each{ |user|
    user.generate_token
    user.save
  }

