/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-апр-2016 6:57:41 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `categories` CASCADE
;

DROP TABLE IF EXISTS `comments` CASCADE
;

DROP TABLE IF EXISTS `countries` CASCADE
;

DROP TABLE IF EXISTS `currencies` CASCADE
;

DROP TABLE IF EXISTS `deals` CASCADE
;

DROP TABLE IF EXISTS `payment_infos` CASCADE
;

DROP TABLE IF EXISTS `products` CASCADE
;

DROP TABLE IF EXISTS `properties` CASCADE
;

DROP TABLE IF EXISTS `property_parameters` CASCADE
;

DROP TABLE IF EXISTS `property_types` CASCADE
;

DROP TABLE IF EXISTS `property_values` CASCADE
;

DROP TABLE IF EXISTS `roles` CASCADE
;

DROP TABLE IF EXISTS `transactions` CASCADE
;

DROP TABLE IF EXISTS `users` CASCADE
;

/* Create Tables */

CREATE TABLE `categories`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(250) 	 NULL,
	`avatar_link` TEXT 	 NULL,
	`is_archived` BOOL 	 NULL DEFAULT 0,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_category` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `comments`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`rate` TINYINT NOT NULL,
	`text` VARCHAR(250) 	 NULL,
	`product_id` INT 	 NULL,
	`user_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_comment` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `countries`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`phone_code` VARCHAR(50) NOT NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_country` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `currencies`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`code` VARCHAR(5) NOT NULL,
	`rate` DECIMAL(10,4) NOT NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_currency` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `deals`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`seller_id` INT 	 NULL,
	`buyer_id` INT 	 NULL,
	`product_id` INT 	 NULL,
	`price` DECIMAL(12,2) NOT NULL,
	`currency_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_deal` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `payment_infos`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`data` TEXT NOT NULL,
	`currency_id` INT 	 NULL,
	`user_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_payment_info` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `products`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(250) NOT NULL,
	`description` VARCHAR(500) NOT NULL,
	`price` DECIMAL(12,2) NOT NULL,
	`quantity` INT NOT NULL,
	`rating` INT NOT NULL DEFAULT 0,
	`rates_count` INT NOT NULL DEFAULT 0,
	`is_paused` BOOL 	 NULL DEFAULT 0,
	`is_archived` BOOL 	 NULL DEFAULT 0,
	`is_blocked` BOOL 	 NULL DEFAULT 0,
	`currency_id` INT 	 NULL,
	`category_id` INT 	 NULL,
	`owner_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_product` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `properties`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(250) 	 NULL,
	`category_id` INT NOT NULL,
	`property_type_id` INT NOT NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_property_type` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `property_parameters`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`key` INT 	 NULL,
	`value` TEXT NOT NULL,
	`property_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_property_parameters` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `property_types`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(250) 	 NULL,
	`display_name` VARCHAR(50) NOT NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_property_type` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `property_values`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`value` TEXT NOT NULL,
	`property_id` INT 	 NULL,
	`product_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_property_value` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `roles`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) 	 NULL,
	`can_see_products` BOOL 	 NULL DEFAULT 0,
	`can_create_products` BOOL 	 NULL DEFAULT 0,
	`can_create_categories` BOOL 	 NULL DEFAULT 0,
	`can_buy_products` BOOL 	 NULL DEFAULT 0,
	`can_comment` BOOL 	 NULL DEFAULT 0,
	`can_moderate` BOOL 	 NULL DEFAULT 0,
	`can_chat` BOOL 	 NULL DEFAULT 0,
	`can_see_statistics` BOOL 	 NULL DEFAULT 0,
	`can_create_moderators` BOOL 	 NULL DEFAULT 0,
	`can_create_priveleged_users` BOOL 	 NULL DEFAULT 0,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_role` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `transactions`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`sender_id` INT 	 NULL,
	`sender_payment_info_id` INT 	 NULL,
	`receiver_id` INT 	 NULL,
	`reseiver_payment_info_id` INT 	 NULL,
	`price` DECIMAL(10,4) NOT NULL,
	`deal_id` INT 	 NULL,
	`currency_id` INT 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_transaction` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `users`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(254) NOT NULL,
	`login` VARCHAR(50) NOT NULL,
	`encrypted_password` VARCHAR(50) NOT NULL,
	`first_name` VARCHAR(50) NOT NULL,
	`last_name` VARCHAR(50) NOT NULL,
	`passport_id` VARCHAR(50) NOT NULL,
	`avatar_url` TEXT 	 NULL,
	`address_line_1` VARCHAR(250) NOT NULL,
	`address_line_2` VARCHAR(250) 	 NULL,
	`post_index` VARCHAR(50) 	 NULL,
	`phone_number` VARCHAR(50) NOT NULL,
	`birth_date` DATE NOT NULL,
	`is_blocked` BOOL NOT NULL DEFAULT 0,
	`is_archived` BOOL NOT NULL DEFAULT 0,
	`role_id` INT 	 NULL,
	`country_id` INT 	 NULL,
	`token` VARCHAR(50) 	 NULL,
	`token_expires_at` DATETIME 	 NULL,
	`created_at` DATETIME 	 NULL,
	`updated_at` DATETIME 	 NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `categories` 
 ADD INDEX `IXFX_is_archived` (`is_archived` ASC)
;

ALTER TABLE `comments` 
 ADD INDEX `IXFK_comment_product` (`product_id` ASC)
;

ALTER TABLE `comments` 
 ADD INDEX `IXFK_comment_user` (`user_id` ASC)
;

ALTER TABLE `countries` 
 ADD INDEX `IXFX_name` (`name` ASC)
;

ALTER TABLE `countries` 
 ADD INDEX `IXFX_phone_code` (`phone_code` ASC)
;

ALTER TABLE `deals` 
 ADD INDEX `IXFK_deal_product` (`product_id` ASC)
;

ALTER TABLE `deals` 
 ADD INDEX `IXFK_deal_user` (`seller_id` ASC)
;

ALTER TABLE `deals` 
 ADD INDEX `IXFK_deal_user_02` (`buyer_id` ASC)
;

ALTER TABLE `payment_infos` 
 ADD INDEX `IXFK_payment_info_currency` (`currency_id` ASC)
;

ALTER TABLE `payment_infos` 
 ADD INDEX `IXFK_payment_info_user` (`user_id` ASC)
;

ALTER TABLE `products` 
 ADD INDEX `IXFK_product_category` (`category_id` ASC)
;

ALTER TABLE `products` 
 ADD INDEX `IXFK_product_user` (`owner_id` ASC)
;

ALTER TABLE `products` 
 ADD INDEX `IXFX_is_archived` (`is_archived` ASC)
;

ALTER TABLE `properties` 
 ADD INDEX `IXFK_property_property_type` (`property_type_id` ASC)
;

ALTER TABLE `properties` 
 ADD INDEX `IXFK_property_type_category` (`category_id` ASC)
;

ALTER TABLE `property_parameters` 
 ADD INDEX `IXFK_property_parameters_property_type` (`property_id` ASC)
;

ALTER TABLE `property_values` 
 ADD INDEX `IXFK_property_value_product` (`product_id` ASC)
;

ALTER TABLE `property_values` 
 ADD INDEX `IXFK_property_value_property_type` (`property_id` ASC)
;

ALTER TABLE `transactions` 
 ADD INDEX `IXFK_transactions_currencies` (`currency_id` ASC)
;

ALTER TABLE `transactions` 
 ADD INDEX `IXFK_transactions_payment_infos` (`sender_payment_info_id` ASC)
;

ALTER TABLE `transactions` 
 ADD INDEX `IXFK_transactions_payment_infos_02` (`reseiver_payment_info_id` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_user_country` (`country_id` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_user_role` (`role_id` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_login` (`login` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_email` (`email` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IX_token` (`token` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `comments` 
 ADD CONSTRAINT `FK_comment_product`
	FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `comments` 
 ADD CONSTRAINT `FK_comment_user`
	FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `deals` 
 ADD CONSTRAINT `FK_deal_currency`
	FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `deals` 
 ADD CONSTRAINT `FK_deal_product`
	FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `deals` 
 ADD CONSTRAINT `FK_deal_user`
	FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `payment_infos` 
 ADD CONSTRAINT `FK_payment_info_currency`
	FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `payment_infos` 
 ADD CONSTRAINT `FK_payment_info_user`
	FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `products` 
 ADD CONSTRAINT `FK_product_category`
	FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `products` 
 ADD CONSTRAINT `FK_product_currency`
	FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `products` 
 ADD CONSTRAINT `FK_product_user`
	FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `properties` 
 ADD CONSTRAINT `FK_property_property_type`
	FOREIGN KEY (`property_type_id`) REFERENCES `property_types` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `properties` 
 ADD CONSTRAINT `FK_property_type_category`
	FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `property_parameters` 
 ADD CONSTRAINT `FK_property_parameters_property_type`
	FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `property_values` 
 ADD CONSTRAINT `FK_property_value_product`
	FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `property_values` 
 ADD CONSTRAINT `FK_property_value_property_type`
	FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `transactions` 
 ADD CONSTRAINT `FK_transaction_deal`
	FOREIGN KEY (`deal_id`) REFERENCES `deals` (`id`) ON DELETE Set Null ON UPDATE Restrict
;

ALTER TABLE `transactions` 
 ADD CONSTRAINT `FK_transaction_user`
	FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `transactions` 
 ADD CONSTRAINT `FK_transaction_user_02`
	FOREIGN KEY (`receiver_id`) REFERENCES `users` (`id`) ON DELETE Set Null ON UPDATE Restrict
;

ALTER TABLE `transactions` 
 ADD CONSTRAINT `FK_transactions_currencies`
	FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `transactions` 
 ADD CONSTRAINT `FK_transactions_payment_infos`
	FOREIGN KEY (`sender_payment_info_id`) REFERENCES `payment_infos` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `transactions` 
 ADD CONSTRAINT `FK_transactions_payment_infos_02`
	FOREIGN KEY (`reseiver_payment_info_id`) REFERENCES `payment_infos` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_user_country`
	FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_user_role`
	FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
